{application,httpotion,
             [{description,"Fancy HTTP client for Elixir, based on ibrowse.\n"},
              {modules,['Elixir.HTTPotion','Elixir.HTTPotion.AsyncChunk',
                        'Elixir.HTTPotion.AsyncEnd',
                        'Elixir.HTTPotion.AsyncHeaders',
                        'Elixir.HTTPotion.AsyncResponse',
                        'Elixir.HTTPotion.Base',
                        'Elixir.HTTPotion.ErrorResponse',
                        'Elixir.HTTPotion.HTTPError',
                        'Elixir.HTTPotion.Headers',
                        'Elixir.HTTPotion.Response']},
              {registered,[]},
              {vsn,"3.0.2"},
              {applications,[kernel,stdlib,elixir,ssl,ibrowse]}]}.
